BUTTON_ADD_MEDIA = 'input[type="file"]'
BUTTON_ATTACHMENT = 'span[data-icon="clip"]'
BUTTON_SEND_MESSAGE = 'span[data-icon="send"]'
CONTACT_BUTTON_CLOSE = 'button[class="hYtwT"]'
CONTACT_DETAILS = 'span[class="_3Tk1z _27rts"]'
CONTACT_INFO = 'header[class="_1UuMR"]'
CONTACT_NAME = 'span[class="_3ZYWe _27rts"]'
CONVERSE_DETAIL = 'div[class="_2qOtp"]'
ICON_UNREAD_MESSAGE = 'span[class="VOr2j"]'
MESSAGE_BOX = "div[class='_3SvgF _1mHgA copyable-area']"
MESSAGE_INPUT = 'div[class="_1awRl copyable-text selectable-text"]'
MESSAGE_PANEL = 'div[id="pane-side"]'
MESSAGE_TEXT = 'span[class="_1VzZY selectable-text invisible-space copyable-text"]'
MESSAGES = 'div[class="_1RAno message-in focusable-list-item"]'
POUPUP_CONTACT = 'div[class="_30EVj gMRg5"]'
QRCODE = 'canvas[aria-label="Scan me!"]'
RELOAD_QRCODE = 'div[class="n9gYh"]'
